spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmforum?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
